survey:
    excel_file: ../../packages/generator/src/examples/Example_Generate_Survey.xlsx

excel:
    active_script: false

widgets:
    output_info_list:
        - output_folder: ../../example/demo_survey_generator/sections/home
          section: home
        - output_folder: ../../example/demo_survey_generator/sections/end
          section: end

conditionals:
    output_file: ../../example/demo_survey_generator/common/conditionals.tsx

choices:
    output_file: ../../example/demo_survey_generator/common/choices.tsx

input_range:
    output_file: ../../example/demo_survey_generator/common/inputRange.tsx

libelles:
    output_folder: ../../example/demo_survey_generator/locales
    overwrite: true
    section: null
