/*
 * Copyright Polytechnique Montreal and contributors
 *
 * This file is licensed under the MIT License.
 * License text available at https://opensource.org/licenses/MIT
 */
// Tests of the review decision queries that need no database: the SQL they build and the way
// they read the aggregated counts. What the queries do against postgres is tested in
// `reviewDecisions.db.test.ts` and in the `getList` tests of `interviews.db.test.ts`.
import {
    getInterviewReviewStatusFromRow,
    getInterviewReviewStatusWhereClause
} from '../reviewDecisions.db.queries';
import {
    interviewReviewStatusFilterValues,
    type InterviewReviewStatusFilter,
    type ReviewDecisionEffectiveStatus
} from 'evolution-common/lib/services/reviews/types';

// The aggregated counts come from postgres as bigint strings, and are absent for an interview
// nobody reviewed, since it has no aggregated row to join.
// [title, row, expected status]
const statusFromRowCases: [
    string,
    { approval_count?: unknown; rejection_count?: unknown; is_force_approved?: unknown },
    ReviewDecisionEffectiveStatus
][] = [
    ['no aggregated row', {}, 'notReviewed'],
    ['zeroed counts', { approval_count: '0', rejection_count: '0', is_force_approved: false }, 'notReviewed'],
    ['string counts from postgres', { approval_count: '2', rejection_count: '0' }, 'approved'],
    ['numeric counts', { approval_count: 0, rejection_count: 1 }, 'rejected'],
    ['reviewers disagreeing', { approval_count: '1', rejection_count: '1' }, 'conflict'],
    ['force approve over a rejection', { rejection_count: '1', is_force_approved: true }, 'forceApproved']
];

test.each(statusFromRowCases)('getInterviewReviewStatusFromRow: %s', (_title, row, expected) => {
    expect(getInterviewReviewStatusFromRow(row)).toEqual(expected);
});

describe('getInterviewReviewStatusWhereClause', () => {
    test('`all` filters nothing', () => {
        expect(getInterviewReviewStatusWhereClause('all', 'i')).toBeUndefined();
    });

    // Every other value of the dropdown must produce a clause, so that a status added to the
    // filter values is not silently left unfiltered here.
    const filteringValues = interviewReviewStatusFilterValues.filter(
        (value) => value !== 'all'
    ) as InterviewReviewStatusFilter[];

    test.each(filteringValues)('%s filters on the interviews table alias', (status) => {
        const clause = getInterviewReviewStatusWhereClause(status, 'i');
        expect(clause).toContain('i.id');
        // The subqueries are generated by knex and interpolated in the clause: a leftover
        // placeholder would mean a binding was dropped along the way.
        expect(clause).not.toContain('?');
    });
});
