# This workflow is used to generate and build the Demo-Generator application.

name: CI-Generator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  generate-and-build-generator:
    runs-on: ubuntu-24.04 # As of Nov 2024, ubuntu-latest is too old for peotry
    strategy:
      matrix:
        node-version: [22.x]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: copy env file
      run: cp .env.example .env
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install poetry
      run: pipx install poetry
    - name: Run Poetry
      working-directory: packages/evolution-generator
      run: poetry install
    - name: Run Python unit tests
      working-directory: packages/evolution-generator
      run: |
        poetry run pytest -v --disable-warnings --tb=short
    - name: Generate survey
      run: yarn generateSurvey:generator
    - name: Install
      run: yarn
    - name: Format python
      run: yarn format:python
    - name: Check git status after python format
      run: |
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "Code formatting issues found. Please run 'yarn format' locally and commit changes."
          git status
          git diff
          exit 1
        fi
    - name: Compile Evolution
      run: yarn compile
    - name: Compile Generated survey
      run: yarn compile:generator
    - name: Build Client bundle
      run: yarn build:prod:generator
      # Skipped build:admin:generator since we don't have UI for them at the moment
